substitutions:
  device_name: "common"
  friendly_name: "Common"
  
esphome:
  name: "${device_name}"
  friendly_name: "${friendly_name}"


# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  - platform: esphome
  #on_error:
  #- button.press: restart_button

time:
  - platform: homeassistant
    id: homeassistant_time

binary_sensor:
  - platform: status
    name: "Connect"

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "IP Address"
    ssid:
      name: "SSID"
    mac_address:
      name: "MAC Address"

sensor:
  - platform: wifi_signal
    name: "WiFi Strength"
    update_interval: 60s

  - platform: uptime
    name: "Uptime"

button:
  - platform: restart
    id: restart_button
    name: "Reboot"
    entity_category: config

switch:
  - platform: safe_mode
    name: "Safe Mode"
    id: device_safe_mode
    entity_category: config
