
esphome:
  name: ${device_name}
  friendly_name: ${light_name}
  on_boot:
    then:
      - light.control:
          id: my_light
          state: !lambda return id(last_light_state);
      - light.control:
          id: green_led
          state: !lambda return id(last_light_state);
  project:
    name: DiraSmart.Switch-1-NS
    version: "CB3S"

dashboard_import:
  package_import_url: github://jbrandek/esphome-packages/gel-1-cb3s-ns.yaml
  import_full_config: false

bk72xx:
  board: cb3s

#packages:
  #common: github://jbrandek/esphome-packages/common.yaml

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  - platform: esphome
  #on_error:
  #- button.press: restart_button

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${light_name} AP"
    password: "1234567890"

captive_portal:

time:
  - platform: homeassistant
    id: homeassistant_time

globals:
  - id: last_light_state
    type: boolean
    restore_value: yes
    initial_value: "false"

preferences:
  flash_write_interval: 30s #(time in seconds e.g. 30s)

output:
  - platform: gpio
    pin:
      number: P9
    id: switch_output

  - platform: gpio
    pin:
      number: P26
    #inverted: true
    id: green_led_output

  - platform: gpio
    pin:
      number: P11
    #inverted: true
    id: wifi_led_output

light:
  - platform: binary
    restore_mode: RESTORE_DEFAULT_OFF
    name:
    id: my_light
    output: switch_output
    on_turn_on:
      - light.turn_on: green_led
      - light.turn_off: wifi_led
      - globals.set:
          id: last_light_state
          value: "true"
    on_turn_off:
      - light.turn_off: green_led
      - light.turn_on: wifi_led
      - globals.set:
          id: last_light_state
          value: "false"

  - platform: binary
    restore_mode: RESTORE_DEFAULT_OFF
    id: green_led
    output: green_led_output

  - platform: binary
    name: WiFi LED
    restore_mode: RESTORE_DEFAULT_ON
    entity_category: config
    id: wifi_led
    disabled_by_default: true
    output: wifi_led_output

  - platform: status_led
    id: blue_led
    pin:
      number: P23
      #inverted: true

binary_sensor:
  - platform: status
    name: "Connect"
  - platform: gpio
    internal: true
    pin:
      number: P7
      inverted: true
      mode: INPUT_PULLUP
    id: my_button
    name: Button
    on_multi_click:
      - timing:
          #- ON for at most 1s
          - ON for 40ms to 800ms
          - OFF for at least 400ms
        then:
          - light.toggle: my_light
      - timing:
          # 5 click restart
          - ON for 40ms to 400ms
          - OFF for 40ms to 400ms
          - ON for 40ms to 400ms
          - OFF for 40ms to 400ms
          - ON for 40ms to 400ms
          - OFF for 40ms to 400ms
          - ON for 40ms to 400ms
          - OFF for 40ms to 400ms
          - ON for 40ms to 400ms
          - OFF for at least 400ms
        then:
          - button.press:
              id: restart_button

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "IP Address"
    ssid:
      name: "SSID"
    mac_address:
      name: "MAC Address"

sensor:
  - platform: wifi_signal
    name: "WiFi Strength"
    update_interval: 60s

  - platform: uptime
    name: "Uptime"

button:
  - platform: restart
    id: restart_button
    name: "Reboot"
    entity_category: config

switch:
  - platform: safe_mode
    name: "Safe Mode"
    id: device_safe_mode
    entity_category: config
